name: Code Coverage

on: ["push"]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test LeagueOfNations
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          python -m poetry install
      - name: Run tests and collect coverage
        run: poetry run pytest --cov=./ --cov-report=xml
      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v3
